### ISSUE TITLE
Nice work, maybe you can add one reference

### ISSUE THREAD

**Issue by zhangbaijin** [Cooperx521/PyramidDrop#1]
In this work, we prove that in most models, image tokens will show a consistent pattern when facing different prompts: image tokens in deep layers do not work and are all redundant.

@article{zhang2024redundancy,
  title={From Redundancy to Relevance: Enhancing Explainability in Multimodal Large Language Models},
  author={Zhang, Xiaofeng and Shen, Chen and Yuan, Xiaosong and Yan, Shaotian and Xie, Liang and Wang, Wenxiao and Gu, Chaochen and Tang, Hao and Ye, Jieping},
  journal={arXiv preprint arXiv:2406.06579},
  year={2024}
}

**Comment by Cooperx521** [comment]
Thank you for your attention to our work! Although our research focuses on different areas, we will cite this work in future updates due to its contribution to the understanding of information flow in large language models LLMs.

**Comment by zhangbaijin** [comment]
thanks for your time~ Best wishes~ :)
