### ISSUE TITLE
VLMEvalKit evaluation code for the trained model using Open-LLaVA-Next

### ISSUE THREAD

**Issue by YuchenLiu98** [Cooperx521/PyramidDrop#5]
Thanks for your wonderful job. I wonder could you please share the evaluation code based on VLMEvalKit for the trained model using Open-LLaVA-Next? I encounter some problem with this evaluation, and the output seems to be some garbled code ("https...."). Do you have any idea how to solve this problem. Thanks.

**Comment by YuchenLiu98** [comment]
It seems to be the torch version mismatching problem. After modifying the correct version, the trained model on Open-LLaVA-Next outputs a bit long answer (e,g., for AI2D "The main source of energy for guppies, as depicted in the food web diagram, is plants. This is indicated by the arrow pointing from "Plants" to "Guppies," which signifies that guppies feed on plants. Therefore, the correct answer from the options provided is: D. plants"). Usually, it should output one option D without other description. Do you have any idea how to solve this problem. Thanks.

**Comment by Cooperx521** [comment]
Hi~
Single example might mot mean there is somthing wrong, you can output the score to see if it is unusual. And it seems that VLMEvalKit will use gpt to judge which can extrct answers, you can check it again.
