### ISSUE TITLE
Blip2训练过程中是否可使用 PyramidDrop

### ISSUE THREAD

**Issue by rosarubus72** [Cooperx521/PyramidDrop#6]
你好我想问一下我们可以在Blip2—qformer训练过程中使用 PyramidDrop吗

**Comment by Cooperx521** [comment]
Hello~
Blip2—qformer训练过程完全可以使用，实现上没有什么难度，方法也是正交的。
但是需要注意的是，因为qformer在出vision encoder之后就已经压缩了visual information，只剩下了几十个image tokens，这个是时候使用PyramidDrop在LLM阶段再次进行压缩，对于时间上的加速会是比较有限的（image token越多，加速比越高）

**Comment by rosarubus72** [comment]
了解了，感谢回复！
